version: '3'
services:

  python:
    build: ./images/python
    working_dir: /home/hovertaxi
    volumes:
      - ./..:/home/hovertaxi
    ports:
      - "8888:8888"

  mongo:
    build: ./images/mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hovertaxi
      MONGO_INITDB_ROOT_PASSWORD: hovertaxi
      MONGO_INITDB_DATABASE: hovertaxi