version: '3'
services:

  python:
    build: ./images/python
    working_dir: /home/hovertaxi
    volumes:
      - ./..:/home/hovertaxi
    ports:
      - "8888:8888"

  db:
    image: mongo:4
    restart: always
    volumes:
      - ./images/db/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: hovertaxi
      MONGO_INITDB_ROOT_PASSWORD: hovertaxi